// Shared contract for the Remotion episode, the /present Player and the editor preview.
// Data lives in data/slides.json. Every existing field is kept; `visual` and `kind` are new.

export const FPS = 30;
export const WIDTH = 1920;
export const HEIGHT = 1080;
export const TRANSITION_FRAMES = 12; // overlap between consecutive slides
export const DIVIDER_SECONDS = 2.5; // part divider card length
export const SLIDE_TAIL_SECONDS = 0.6; // silence after the last sentence of a slide

export type ThemeName = "ledger" | "whiteboard";

export interface SentenceTiming {
  sentence_idx: number;
  text: string;
  local_start: number; // seconds from slide start
  duration: number; // seconds of speech
  global_start: number; // seconds from episode start (informational)
}

export interface ScriptLine {
  sentence_idx: number;
  text: string;
  duration_s: number;
  pause_s: number; // 0.35–0.75, becomes a timeline gap after the sentence
  expression: string; // free text, e.g. "wry", "cautionary", "emphatic", "warm", "neutral"
}

export interface VideoScript {
  chapter_vibe: string;
  tone: string;
  pacing: string;
  director_note: string;
  script_lines: ScriptLine[];
}

export type Visual =
  | { type: "receipt"; title: string; sub?: string; lines: { label: string; value: string }[]; total?: { label: string; value: string }; note?: string }
  | { type: "bars"; title: string; sub?: string; items: { label: string; value: number; display: string }[] }
  | { type: "range"; title: string; sub?: string; min: number; max: number; unit: string; markers: { label: string; value: number }[] }
  | { type: "compare"; title: string; left: { title: string; rows: string[] }; right: { title: string; rows: string[] } }
  | { type: "logos"; title: string; items: { label: string; sub?: string }[] }
  | { type: "tree"; title: string; root: string; branches: { q: string; yes: string; no: string }[] }
  | { type: "photo"; src: string; caption: string; credit?: string } // src relative to /assets
  | { type: "character"; src: string; caption: string }
  | { type: "icon"; src: string; stat: string; caption: string };

export type SlideKind = "cold_open" | "chapter" | "end_card";

export interface Slide {
  id: string; // b01..b20, plus "open" and "end"
  index: number; // 0 = cold open, 1..20 chapters, 21 = end card
  kind?: SlideKind; // default "chapter"
  part: string;
  headline: string;
  chip: string;
  image: string; // legacy static PNG, still used by the editor fallback
  bullets: string[];
  sentences: string[];
  audio: string; // legacy per-slide mp3 path
  duration: number; // seconds, regenerated by scripts/gen-vo.mjs
  sentence_timings: SentenceTiming[];
  video_script?: VideoScript;
  visual?: Visual;
}

export interface Theme {
  name: ThemeName;
  paper: string;
  paper2: string;
  ink: string;
  inkSoft: string;
  accent: string;
  accentSoft: string;
  accent2: string; // secondary marker / chart colour
  mute: string;
  line: string;
  fontBody: string;
  fontDisplay: string;
  fontMono: string;
  radius: number;
  strokeStyle: "clean" | "marker";
}

export interface EpisodeProps {
  theme: ThemeName;
  captions: boolean;
  muted?: boolean; // true = render no <Audio> (stills, smoke tests before VO exists)
}

// Absolute frame positions on the TransitionSeries timeline.
// Item i starts at sum(previous durations) - i * TRANSITION_FRAMES.
export interface TimelineItem {
  kind: "divider" | "slide";
  slideIndex?: number; // index into the slides array for kind === "slide"
  part?: string; // for dividers
  partNumber?: number; // 1..6
  startFrame: number;
  durationFrames: number;
  sentenceStartFrames: number[]; // absolute frames, one per sentence (empty for dividers)
}

export interface Timeline {
  items: TimelineItem[];
  totalFrames: number;
}

/*
Component contracts (implemented by the workers):

remotion/visuals/index.tsx
  export const SlideVisual: React.FC<{ visual: Visual; theme: Theme; frame: number; activeSentence: number; width: number; height: number }>
  `frame` is local to the slide (0 at slide start). Every animation is a pure function of frame.

remotion/Episode.tsx
  export const buildTimeline: (slides: Slide[]) => Timeline
  export const Episode: React.FC<EpisodeProps>   // loads slides via getSlides()
  export const getSlides: () => Slide[]           // imports data/slides.json

remotion/Root.tsx
  <Composition id="CafeEpisode" component={Episode} calculateMetadata=... defaultProps={{theme:"ledger",captions:true}} />
*/
