#!/usr/bin/env node
// Renders SCRIPT.md from data/slides.json: the human-readable narration script,
// one section per slide, plus a total runtime estimate.
//
// Reads data/slides.json fresh at run time; writes only SCRIPT.md (never touches
// slides.json).

import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const SLIDES_PATH = path.resolve("data/slides.json");
const OUT_PATH = path.resolve("SCRIPT.md");
const DIVIDER_SECONDS = 2.5;
const DEFAULT_PAUSE_S = 0.4;

function pad2(n) {
  return String(n).padStart(2, "0");
}

function fmtSeconds(s) {
  return `${s.toFixed(2)}s`;
}

function main() {
  const slides = JSON.parse(readFileSync(SLIDES_PATH, "utf8"));

  const lines = [];
  lines.push("# Bangalore Café — Episode Script");
  lines.push("");
  lines.push(`_Generated by scripts/export-script.mjs from data/slides.json — do not hand-edit._`);
  lines.push("");

  let prevPart = null;
  let totalRuntime = 0;

  for (const slide of slides) {
    if (prevPart !== null && slide.part !== prevPart) {
      totalRuntime += DIVIDER_SECONDS;
    }
    prevPart = slide.part;
    totalRuntime += typeof slide.duration === "number" ? slide.duration : 0;

    lines.push(`## ${pad2(slide.index)} · ${slide.headline}`);
    lines.push("");
    lines.push(`**Part:** ${slide.part}  `);
    lines.push(`**Chip:** ${slide.chip}`);
    lines.push("");

    const vs = slide.video_script;
    if (vs) {
      if (vs.chapter_vibe) lines.push(`**Chapter vibe:** ${vs.chapter_vibe}  `);
      if (vs.tone) lines.push(`**Tone:** ${vs.tone}  `);
      if (vs.pacing) lines.push(`**Pacing:** ${vs.pacing}`);
      lines.push("");
      if (vs.director_note) {
        lines.push(`> ${vs.director_note}`);
        lines.push("");
      }
    }

    const scriptLines = vs?.script_lines || [];
    const sentences = slide.sentences || [];
    sentences.forEach((text, i) => {
      const line = scriptLines[i];
      const expression = line?.expression ? line.expression : "neutral";
      const pause = line?.pause_s ?? DEFAULT_PAUSE_S;
      lines.push(`${i + 1}. (${expression}) "${text}" [pause ${pause.toFixed(2)}s]`);
    });
    lines.push("");
  }

  lines.push("---");
  lines.push("");
  lines.push(`**Total runtime estimate:** ${fmtSeconds(totalRuntime)} (~${(totalRuntime / 60).toFixed(1)} min)`);
  lines.push("");

  writeFileSync(OUT_PATH, lines.join("\n"));
  console.log(`Wrote ${OUT_PATH} (${slides.length} slides, ~${fmtSeconds(totalRuntime)} total)`);
}

main();
